# Generated by Django 5.0.4 on 2024-05-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='group_name',
            field=models.CharField(default='Group_name', max_length=250, null=True),
        ),
    ]
