# Generated by Django 5.0.4 on 2024-05-08 00:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
