# Generated by Django 5.0.6 on 2024-06-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customusermodel_friends_delete_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='password',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
