# Generated by Django 5.0.6 on 2024-06-24 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_customusermodel_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='image_url',
            field=models.URLField(default='https://www.google.com.np/maps/@27.6775629,85.3111535,17z?entry=ttu', max_length=5000, unique=False, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
            preserve_default=False,
        ),
    ]
