# Generated by Django 5.0.6 on 2024-06-25 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customusermodel_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='image_url',
            field=models.URLField(max_length=50000, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
    ]
